### ISSUE TITLE
controllermanager.go version is not shown in the log correctly

### ISSUE THREAD

**Issue by nicolehanjing** [kubernetes/cloud-provider#53] opened 2021-12-02 18:06 UTC
controllermanager.go version is shown as `v0.0.0-master+$Format:%H$` in the log:
```
I1201 10:00:32.996725       1 controllermanager.go:142] Version: v0.0.0-master+$Format:%H$
```

https://github.com/kubernetes/cloud-provider/blob/master/app/controllermanager.go#L144 needs to be fixed

Expected to see a real version number instead of `v0.0.0-master+$Format:%H$`.

Ref: https://github.com/kubernetes/cloud-provider-vsphere/issues/534

**Comment by displague** [comment] 2021-12-15 17:19
This seems to be a duplicate of #49

**Comment by andrewsykim** [comment] 2022-03-02 17:40
I think this is working as expected. You need to use the version build tag when compiling the binary for the proper version to be displayed. 

/close

**Closed** 2022-03-02 17:40 UTC
